import { Database, FolderOpen } from 'lucide-react'
import { useSettings, useUpdateSettings } from '../hooks/useMetrics'
import { LoadingState } from '../components/common/LoadingState'

function Toggle({ value, onChange }: { value: boolean; onChange: (value: boolean) => void }) { return <button onClick={()=>onChange(!value)} className={`relative h-6 w-11 rounded-full transition ${value?'bg-indigo-500':'bg-zinc-700'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${value?'left-6':'left-1'}`}/></button> }

export function SettingsView() {
  const { data, error } = useSettings(); const update=useUpdateSettings()
  if (!data) return <LoadingState error={error}/>
  const change = (values: Parameters<typeof update.mutate>[0]) => update.mutate(values)
  return <><div className="mb-7"><h1 className="text-2xl font-semibold">Settings</h1><p className="mt-1 text-sm text-zinc-500">Control local collection and desktop behavior.</p></div><div className="panel divide-y divide-white/[0.06]"><div className="flex items-center justify-between p-5"><div><div className="text-sm font-medium">Launch at login</div><div className="mt-1 text-xs text-zinc-500">Start monitoring after you sign in.</div></div><Toggle value={data.launch_at_login} onChange={async value=>{await window.desktop?.setLoginItem(value);change({launch_at_login:value})}}/></div><div className="flex items-center justify-between p-5"><div><div className="text-sm font-medium">Minimize to tray</div><div className="mt-1 text-xs text-zinc-500">Keep the collector available when the window closes.</div></div><Toggle value={data.minimize_to_tray} onChange={value=>change({minimize_to_tray:value})}/></div><div className="flex items-center justify-between p-5"><div><div className="text-sm font-medium">Scan interval</div><div className="mt-1 text-xs text-zinc-500">How often local usage logs are refreshed.</div></div><select value={data.scan_interval_seconds} onChange={e=>change({scan_interval_seconds:Number(e.target.value)})} className="rounded-lg border border-white/10 bg-zinc-900 px-3 py-2 text-sm"><option value={15}>15 seconds</option><option value={30}>30 seconds</option><option value={60}>1 minute</option><option value={300}>5 minutes</option></select></div></div><div className="panel mt-4 p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-white/[0.05] text-zinc-400"><Database size={17}/></span><div className="min-w-0 flex-1"><div className="text-sm font-medium">Local data directory</div><div className="mt-1 truncate font-mono text-xs text-zinc-600">{data.data_dir}</div></div><button className="button" onClick={()=>window.desktop?.openPath(data.data_dir)}><FolderOpen size={14}/>Open</button></div></div><p className="mt-4 text-xs leading-5 text-zinc-600">Provider credentials are read from their existing environment or credential stores and are never copied into the Hubble database.</p></>
}
